### ISSUE TITLE
Which columns to use in order to join the 3 data sets?

### ISSUE THREAD

**Issue by aliarsalankazmi** [isawnyu/pleiades-dump#5]
Hi

Can you please indicate how each of the 3 data sets are to be joined with each other - the column names - and whether it is normal to expect duplicate records if the data sets are merged?

I was merging the location and names data sets to places data set using pid = path, but I end up getting duplicate rows.

Thanks a lot

**Comment by ryanfb** [comment]
I think duplicates will depend on how you are doing the join. I believe join tools like [csvkit's `csvjoin`](http://csvkit.readthedocs.io/en/1.0.1/scripts/csvjoin.html) will output a row for each match on the join column. Since a single place can have many names and locations, this will result in a "duplicate" place row for every associated name and location.

For example, https://pleiades.stoa.org/places/109126 has names https://pleiades.stoa.org/places/109126/paris and https://pleiades.stoa.org/places/109126/loutokotia. A simple join will output a CSV that has all the data for the place 109126 at least twice, once with the data for the name "Paris" and a second time with the data for the name "Loutokotia".

In order to join them onto a single row (in CSV) you would need to define how you want to collapse multiple values into a single column in a structured way, which isn't straightforward with data that has one-to-many relationships like this - a single CSV just isn't well-suited to it. The JSON serialization, for example, can capture these relationships in a single file due to the way JSON is structured.

**Comment by aliarsalankazmi** [comment]
@ryanfb Thanks ever so much; makes perfect sense.
